site_name: piano-lesson-pieces
nav:
  - Home: index.md
  - Repertoire 2: repertoire2.md
  - Solfege and Ensemble 2: solfege-and-ensemble2.md
  - Repertoire 1: repertoire1.md
  - Solfege and Ensemble 1: solfege-and-ensemble1.md
  - Primary 4: primary4.md
  - Primary 3: primary3.md
  - Primary 2: primary2.md
  - Primary 1: primary1.md
theme:
  name: material
  favicon: https://cdn3.iconfinder.com/data/icons/piano-keyboard/900/4-512.png
  logo: https://cdn3.iconfinder.com/data/icons/piano-keyboard/900/4-512.png
  font:
    text: Roboto
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: deep purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - header.autohide
    - navigation.top
    - navigation.footer
repo_name: piano-lesson-pieces
repo_url: https://github.com/cutiepie-kitty-ada/piano-lesson-pieces
plugins:
  - search
  - minify:
      minify_html: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cutiepie-kitty-ada
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/adalipiano
