site_name: piano-lesson-pieces
nav:
  - Home: index.md
  - Books:
    - books/index.md
    - RCM 1 Piano Repertoire: books/rcm1-repertoire.md
    - RCM 1 Piano Etudes: books/rcm1-etudes.md
    - Modern Course For The Piano 1: books/modern-course1.md
    - Easiest Piano Course Part 3: books/easiest-piano-course3.md
    - Easiest Piano Course Part 2: books/easiest-piano-course2.md
    - Repertoire 2: books/repertoire2.md
    - Solfege and Ensemble 2: books/solfege-and-ensemble2.md
    - Repertoire 1: books/repertoire1.md
    - Solfege and Ensemble 1: books/solfege-and-ensemble1.md
    - Primary 4: books/primary4.md
    - Primary 3: books/primary3.md
    - Primary 2: books/primary2.md
    - Primary 1: books/primary1.md
  - Tags: tags.md
theme:
  name: material
  favicon: https://cdn3.iconfinder.com/data/icons/piano-keyboard/900/4-512.png
  logo: https://cdn3.iconfinder.com/data/icons/piano-keyboard/900/4-512.png
  font:
    text: Roboto
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: deep purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - header.autohide
    - navigation.top
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
repo_name: piano-lesson-pieces
repo_url: https://github.com/cutiepie-kitty-ada/piano-lesson-pieces
plugins:
  - search
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
      minify_css: true
      css_files:
        - css/neoteroi-mkdocs.css
  - neoteroi.contribs:
      contributors:
        - email: imzehengl@gmail.com
          image: https://avatars.githubusercontent.com/u/6238966?v=4
        - email: 156275145+cutiepie-kitty-ada@users.noreply.github.com
          image: https://avatars.githubusercontent.com/u/156275145?v=4
extra_css:
  - css/neoteroi-mkdocs.css
markdown_extensions:
  - neoteroi.timeline
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cutiepie-kitty-ada
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/adalipiano
